# Generated by Django 3.2.5 on 2021-07-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active_days',
            field=models.IntegerField(default=31, max_length=62),
        ),
    ]
