# Generated by Django 3.2.5 on 2021-07-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20210717_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='active_days',
        ),
    ]
