# Generated by Django 3.2.5 on 2021-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_skills',
        ),
        migrations.AddField(
            model_name='job',
            name='job_skills',
            field=models.ManyToManyField(blank=True, null=True, to='viewer.Skill'),
        ),
    ]
