# Generated by Django 3.2.5 on 2021-07-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20210724_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_skills',
            field=models.ManyToManyField(blank=True, to='viewer.Skill'),
        ),
    ]
